apiVersion: v1
kind: Service
metadata:
  name: fail2ban-metrics-exporter
  labels:
    app: fail2ban-metrics-exporter
spec:
  ports:
    - port: 9191
      targetPort: 9191
      protocol: TCP
      name: metrics
  selector:
    app: fail2ban-metrics-exporter