apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fail2ban-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fail2ban-metrics-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s