apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 1
  enableSuperuserAccess: true
  storage:
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-creds
