apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielPortovedo/home_server'
    path: argocd-applications/media/prowlarr/prowlarr_resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
