apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argo/argocd-self.yaml

  # cert-manager
  - ./cert-manager/cert-manager-app.yaml
  - ./cert-manager/cert-manager-resources-app.yaml

  # home-assistant
  # - ./home-assistant/home_assistant_app.yaml

  # immich
  - ./immich/immich_app.yaml
  - ./immich/immich_resources_app.yaml

  # media
  ## jellyfin
  - ./media/jellyfin/jellyfin_app.yaml
  - ./media/jellyfin/jellyfin_resources_app.yaml
  ## qbittorrent
  - ./media/qbittorrent/qbittorrent_app.yaml
  ## prowlarr
  # - ./media/prowlarr/prowlarr_app.yaml

  ## radarr
  # - ./media/radarr/radarr_app.yaml
  # minecraft
  # - ./minecraft/minecraft_app.yaml
  # - ./minecraft/minecraft_resources_app.yaml

  # monitoring
  - ./monitoring/kube_prometheus_stack_app.yaml
  - ./monitoring/kube_prometheus_stack_resources_app.yaml
  - ./monitoring/fail2ban_exporter.yaml

  # nextcloud
  - ./nextcloud/next_cloud_app.yaml

  # pihole
  - ./pihole/pihole_resources_app.yaml
  - ./pihole/pihole_app.yaml

  # Postgres
  - ./postgres/pg_db_operator_app.yaml
  - ./postgres/pg_dbs_resources_app.yaml
