apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-pg-db-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielPortovedo/home_server'
    path: argocd-applications/postgres/immich_pg_db_resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

